### ISSUE TITLE
Unable to set profile photo

### ISSUE THREAD

**Issue by dryabov** [joomla/volunteers.joomla.org#262]
There is no type=file field on the identify portal, just a text "Access Denied" displayed (see screenshot)
![2021-09-02 21_18_24-Your Joomla Identity Profile](https://user-images.githubusercontent.com/378044/131896290-07e5ebb2-50a1-4f83-b379-bef2903e6364.png)
How to fix it?

**Comment by sanderpotjer** [comment]
@dryabov thanks for reporting the issue, this should be fixed now so you can upload an image.

**Comment by dryabov** [comment]
After click on the "Insert" button, the photo is not uploaded, and there are following error messages in the browser's console log (query part of pwtimage.min.js URL is removed for simplicity, and a part of the token is replaced by `...`):
```
10:01:14.209 pwtimage.min.js:1 Refused to connect to 'blob:https://identity.joomla.org/739339c0-...-e1c10c5b8c87' because it violates the following Content Security Policy directive: "connect-src 'self' https://*.joomla.org https://*.pingdom.net https://*.google-analytics.com https://*.doubleclick.net https://apikeys.civiccomputing.com".
10:01:14.230 pwtimage.min.js:1 XHR failed loading: GET "blob:https://identity.joomla.org/739339c0-...-e1c10c5b8c87".
10:01:14.403 pwtimage.min.js:1 POST https://community.joomla.org/scripts/csp-reporter.php?source=identity.joomla.org 403
```

**Comment by sanderpotjer** [comment]
@conconnl can you please correct the CSP settings to allow blob.

**Comment by conconnl** [comment]
@sanderpotjer the PR should fix it.

**Comment by dryabov** [comment]
It still doesn't work.

And there is an issue in the page source: `onclick` event contains URL encoded like it would be in HTML context instead of JS string context:
```
onclick="jQuery('iframe#pwtImageFrame-61321b4c46aeb').attr('src', 'https://identity.joomla.org/index.php?option=com_pwtimage&amp;view=image&amp;tmpl=component&modalId=...'); pwtImage.setTargetId('61321b4c46aeb')"
```
Note `&amp;` is used (twice) instead of just an `&`.

**Comment by sanderpotjer** [comment]
@dryabov the PR means a Pull Request, which needs to be merged and released first before the fix is applied. So it is correct that it stil doesn't work (yet)

**Comment by sanderpotjer** [comment]
@dryabov apologizes for the delay, it turned out to be a combination of issues and not for all accounts. All should be fine now.
